import Image from "next/image";
import Link from "next/link";
import { COMPANY_EMAIL, COMPANY_PHONE, COMPANY_LOGO } from "@/lib/site";
import { COMPANY_LINKEDIN_URL } from "@/data/companyProfile";
export default function Footer() {
 return <footer className="trade-footer"><div className="wrap">
 <div className="footer-top"><div><Link href="/" className="trade-brand"><Image src={COMPANY_LOGO} alt="Enreach Global logo" width={150} height={100} unoptimized/><span><small>GLOBAL METAL TRADE</small></span></Link><p>A global buying partner for industrial metal supply.<br/>Aluminium. Copper.</p><div className="footer-socials">{!COMPANY_LINKEDIN_URL.includes("company-linkedin-url") && <a href={COMPANY_LINKEDIN_URL} target="_blank" rel="noopener noreferrer"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M5 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4ZM3 9h4v12H3Zm6 0h4v1.6c.6-1 1.7-1.9 3.5-1.9 3 0 4.5 1.8 4.5 5.2V21h-4v-6.2c0-1.6-.6-2.6-1.9-2.6-1.4 0-2.1 1-2.1 2.6V21H9Z"/></svg>LinkedIn</a>}<a href="https://www.instagram.com/enreach_global?igsi=NW56dXA2bHV2MTN2" target="_blank" rel="noopener noreferrer"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>Instagram</a></div></div><Link className="trade-button" href="/contact">Sell your scrap ↗</Link></div>
 <div className="footer-columns"><div><span className="eyebrow">Explore</span><Link href="/what-we-buy">What we buy</Link><Link href="/#mission-vision">Mission & vision</Link><Link href="/#industries">Industries</Link><Link href="/#about">Our story</Link></div><div><span className="eyebrow">Connect</span><Link href="/#locations">Global reach</Link><Link href="/blog">Insights</Link><Link href="/contact">Contact</Link>{!COMPANY_LINKEDIN_URL.includes("company-linkedin-url") && <a href={COMPANY_LINKEDIN_URL} target="_blank" rel="noreferrer">LinkedIn ↗</a>}</div><div><span className="eyebrow">Let's talk metal</span><a href={`mailto:${COMPANY_EMAIL}`}>{COMPANY_EMAIL}</a><a href={`tel:${COMPANY_PHONE.replace(/\s/g,"")}`}>{COMPANY_PHONE}</a><p>Calgary, Alberta, Canada</p></div></div>
 <div className="footer-bottom"><span>© {new Date().getFullYear()} Enreach Global Inc.</span><a className="footer-credit" href="https://www.ecliptixsolutions.com/" target="_blank" rel="noopener noreferrer">Designed and Developed by Ecliptix Solutions</a><Link className="footer-privacy" href="/privacy-policy">Privacy policy</Link></div><p className="footer-tagline">Global sourcing. Reliable execution.</p>
 </div></footer>;
}
